version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fullstack-backend
    ports:
      - "8085:8085"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: fullstack-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge